// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/aether.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProtocolType int32

const (
	ProtocolType_PROTOCOL_UNKNOWN ProtocolType = 0
	ProtocolType_UNISWAP_V2       ProtocolType = 1
	ProtocolType_UNISWAP_V3       ProtocolType = 2
	ProtocolType_SUSHISWAP        ProtocolType = 3
	ProtocolType_CURVE            ProtocolType = 4
	ProtocolType_BALANCER_V2      ProtocolType = 5
	ProtocolType_BANCOR_V3        ProtocolType = 6
)

// Enum value maps for ProtocolType.
var (
	ProtocolType_name = map[int32]string{
		0: "PROTOCOL_UNKNOWN",
		1: "UNISWAP_V2",
		2: "UNISWAP_V3",
		3: "SUSHISWAP",
		4: "CURVE",
		5: "BALANCER_V2",
		6: "BANCOR_V3",
	}
	ProtocolType_value = map[string]int32{
		"PROTOCOL_UNKNOWN": 0,
		"UNISWAP_V2":       1,
		"UNISWAP_V3":       2,
		"SUSHISWAP":        3,
		"CURVE":            4,
		"BALANCER_V2":      5,
		"BANCOR_V3":        6,
	}
)

func (x ProtocolType) Enum() *ProtocolType {
	p := new(ProtocolType)
	*p = x
	return p
}

func (x ProtocolType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProtocolType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_aether_proto_enumTypes[0].Descriptor()
}

func (ProtocolType) Type() protoreflect.EnumType {
	return &file_proto_aether_proto_enumTypes[0]
}

func (x ProtocolType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProtocolType.Descriptor instead.
func (ProtocolType) EnumDescriptor() ([]byte, []int) {
	return file_proto_aether_proto_rawDescGZIP(), []int{0}
}

type SystemState int32

const (
	SystemState_STATE_UNKNOWN SystemState = 0
	SystemState_RUNNING       SystemState = 1
	SystemState_DEGRADED      SystemState = 2
	SystemState_PAUSED        SystemState = 3
	SystemState_HALTED        SystemState = 4
)

// Enum value maps for SystemState.
var (
	SystemState_name = map[int32]string{
		0: "STATE_UNKNOWN",
		1: "RUNNING",
		2: "DEGRADED",
		3: "PAUSED",
		4: "HALTED",
	}
	SystemState_value = map[string]int32{
		"STATE_UNKNOWN": 0,
		"RUNNING":       1,
		"DEGRADED":      2,
		"PAUSED":        3,
		"HALTED":        4,
	}
)

func (x SystemState) Enum() *SystemState {
	p := new(SystemState)
	*p = x
	return p
}

func (x SystemState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SystemState) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_aether_proto_enumTypes[1].Descriptor()
}

func (SystemState) Type() protoreflect.EnumType {
	return &file_proto_aether_proto_enumTypes[1]
}

func (x SystemState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SystemState.Descriptor instead.
func (SystemState) EnumDescriptor() ([]byte, []int) {
	return file_proto_aether_proto_rawDescGZIP(), []int{1}
}

type SwapStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      ProtocolType           `protobuf:"varint,1,opt,name=protocol,proto3,enum=aether.ProtocolType" json:"protocol,omitempty"`
	PoolAddress   []byte                 `protobuf:"bytes,2,opt,name=pool_address,json=poolAddress,proto3" json:"pool_address,omitempty"`
	TokenIn       []byte                 `protobuf:"bytes,3,opt,name=token_in,json=tokenIn,proto3" json:"token_in,omitempty"`
	TokenOut      []byte                 `protobuf:"bytes,4,opt,name=token_out,json=tokenOut,proto3" json:"token_out,omitempty"`
	AmountIn      []byte                 `protobuf:"bytes,5,opt,name=amount_in,json=amountIn,proto3" json:"amount_in,omitempty"`
	MinAmountOut  []byte                 `protobuf:"bytes,6,opt,name=min_amount_out,json=minAmountOut,proto3" json:"min_amount_out,omitempty"`
	Calldata      []byte                 `protobuf:"bytes,7,opt,name=calldata,proto3" json:"calldata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwapStep) Reset() {
	*x = SwapStep{}
	mi := &file_proto_aether_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwapStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwapStep) ProtoMessage() {}

func (x *SwapStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwapStep.ProtoReflect.Descriptor instead.
func (*SwapStep) Descriptor() ([]byte, []int) {
	return file_proto_aether_proto_rawDescGZIP(), []int{0}
}

func (x *SwapStep) GetProtocol() ProtocolType {
	if x != nil {
		return x.Protocol
	}
	return ProtocolType_PROTOCOL_UNKNOWN
}

func (x *SwapStep) GetPoolAddress() []byte {
	if x != nil {
		return x.PoolAddress
	}
	return nil
}

func (x *SwapStep) GetTokenIn() []byte {
	if x != nil {
		return x.TokenIn
	}
	return nil
}

func (x *SwapStep) GetTokenOut() []byte {
	if x != nil {
		return x.TokenOut
	}
	return nil
}

func (x *SwapStep) GetAmountIn() []byte {
	if x != nil {
		return x.AmountIn
	}
	return nil
}

func (x *SwapStep) GetMinAmountOut() []byte {
	if x != nil {
		return x.MinAmountOut
	}
	return nil
}

func (x *SwapStep) GetCalldata() []byte {
	if x != nil {
		return x.Calldata
	}
	return nil
}

type ArbHop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      ProtocolType           `protobuf:"varint,1,opt,name=protocol,proto3,enum=aether.ProtocolType" json:"protocol,omitempty"`
	PoolAddress   []byte                 `protobuf:"bytes,2,opt,name=pool_address,json=poolAddress,proto3" json:"pool_address,omitempty"`
	TokenIn       []byte                 `protobuf:"bytes,3,opt,name=token_in,json=tokenIn,proto3" json:"token_in,omitempty"`
	TokenOut      []byte                 `protobuf:"bytes,4,opt,name=token_out,json=tokenOut,proto3" json:"token_out,omitempty"`
	AmountIn      []byte                 `protobuf:"bytes,5,opt,name=amount_in,json=amountIn,proto3" json:"amount_in,omitempty"`
	ExpectedOut   []byte                 `protobuf:"bytes,6,opt,name=expected_out,json=expectedOut,proto3" json:"expected_out,omitempty"`
	EstimatedGas  uint64                 `protobuf:"varint,7,opt,name=estimated_gas,json=estimatedGas,proto3" json:"estimated_gas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArbHop) Reset() {
	*x = ArbHop{}
	mi := &file_proto_aether_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArbHop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArbHop) ProtoMessage() {}

func (x *ArbHop) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArbHop.ProtoReflect.Descriptor instead.
func (*ArbHop) Descriptor() ([]byte, []int) {
	return file_proto_aether_proto_rawDescGZIP(), []int{1}
}

func (x *ArbHop) GetProtocol() ProtocolType {
	if x != nil {
		return x.Protocol
	}
	return ProtocolType_PROTOCOL_UNKNOWN
}

func (x *ArbHop) GetPoolAddress() []byte {
	if x != nil {
		return x.PoolAddress
	}
	return nil
}

func (x *ArbHop) GetTokenIn() []byte {
	if x != nil {
		return x.TokenIn
	}
	return nil
}

func (x *ArbHop) GetTokenOut() []byte {
	if x != nil {
		return x.TokenOut
	}
	return nil
}

func (x *ArbHop) GetAmountIn() []byte {
	if x != nil {
		return x.AmountIn
	}
	return nil
}

func (x *ArbHop) GetExpectedOut() []byte {
	if x != nil {
		return x.ExpectedOut
	}
	return nil
}

func (x *ArbHop) GetEstimatedGas() uint64 {
	if x != nil {
		return x.EstimatedGas
	}
	return 0
}

type ValidatedArb struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hops            []*ArbHop              `protobuf:"bytes,2,rep,name=hops,proto3" json:"hops,omitempty"`
	TotalProfitWei  []byte                 `protobuf:"bytes,3,opt,name=total_profit_wei,json=totalProfitWei,proto3" json:"total_profit_wei,omitempty"`
	TotalGas        uint64                 `protobuf:"varint,4,opt,name=total_gas,json=totalGas,proto3" json:"total_gas,omitempty"`
	GasCostWei      []byte                 `protobuf:"bytes,5,opt,name=gas_cost_wei,json=gasCostWei,proto3" json:"gas_cost_wei,omitempty"`
	NetProfitWei    []byte                 `protobuf:"bytes,6,opt,name=net_profit_wei,json=netProfitWei,proto3" json:"net_profit_wei,omitempty"`
	BlockNumber     uint64                 `protobuf:"varint,7,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
	TimestampNs     int64                  `protobuf:"varint,8,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	FlashloanToken  []byte                 `protobuf:"bytes,9,opt,name=flashloan_token,json=flashloanToken,proto3" json:"flashloan_token,omitempty"`
	FlashloanAmount []byte                 `protobuf:"bytes,10,opt,name=flashloan_amount,json=flashloanAmount,proto3" json:"flashloan_amount,omitempty"`
	Steps           []*SwapStep            `protobuf:"bytes,11,rep,name=steps,proto3" json:"steps,omitempty"`
	Calldata        []byte                 `protobuf:"bytes,12,opt,name=calldata,proto3" json:"calldata,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ValidatedArb) Reset() {
	*x = ValidatedArb{}
	mi := &file_proto_aether_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatedArb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatedArb) ProtoMessage() {}

func (x *ValidatedArb) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatedArb.ProtoReflect.Descriptor instead.
func (*ValidatedArb) Descriptor() ([]byte, []int) {
	return file_proto_aether_proto_rawDescGZIP(), []int{2}
}

func (x *ValidatedArb) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ValidatedArb) GetHops() []*ArbHop {
	if x != nil {
		return x.Hops
	}
	return nil
}

func (x *ValidatedArb) GetTotalProfitWei() []byte {
	if x != nil {
		return x.TotalProfitWei
	}
	return nil
}

func (x *ValidatedArb) GetTotalGas() uint64 {
	if x != nil {
		return x.TotalGas
	}
	return 0
}

func (x *ValidatedArb) GetGasCostWei() []byte {
	if x != nil {
		return x.GasCostWei
	}
	return nil
}

func (x *ValidatedArb) GetNetProfitWei() []byte {
	if x != nil {
		return x.NetProfitWei
	}
	return nil
}

func (x *ValidatedArb) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *ValidatedArb) GetTimestampNs() int64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *ValidatedArb) GetFlashloanToken() []byte {
	if x != nil {
		return x.FlashloanToken
	}
	return nil
}

func (x *ValidatedArb) GetFlashloanAmount() []byte {
	if x != nil {
		return x.FlashloanAmount
	}
	return nil
}

func (x *ValidatedArb) GetSteps() []*SwapStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *ValidatedArb) GetCalldata() []byte {
	if x != nil {
		return x.Calldata
	}
	return nil
}

type SubmitArbResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	BundleHash    string                 `protobuf:"bytes,2,opt,name=bundle_hash,json=bundleHash,proto3" json:"bundle_hash,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitArbResponse) Reset() {
	*x = SubmitArbResponse{}
	mi := &file_proto_aether_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitArbResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitArbResponse) ProtoMessage() {}

func (x *SubmitArbResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitArbResponse.ProtoReflect.Descriptor instead.
func (*SubmitArbResponse) Descriptor() ([]byte, []int) {
	return file_proto_aether_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitArbResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SubmitArbResponse) GetBundleHash() string {
	if x != nil {
		return x.BundleHash
	}
	return ""
}

func (x *SubmitArbResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StreamArbsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinProfitEth  float64                `protobuf:"fixed64,1,opt,name=min_profit_eth,json=minProfitEth,proto3" json:"min_profit_eth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamArbsRequest) Reset() {
	*x = StreamArbsRequest{}
	mi := &file_proto_aether_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamArbsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamArbsRequest) ProtoMessage() {}

func (x *StreamArbsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamArbsRequest.ProtoReflect.Descriptor instead.
func (*StreamArbsRequest) Descriptor() ([]byte, []int) {
	return file_proto_aether_proto_rawDescGZIP(), []int{4}
}

func (x *StreamArbsRequest) GetMinProfitEth() float64 {
	if x != nil {
		return x.MinProfitEth
	}
	return 0
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_aether_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_aether_proto_rawDescGZIP(), []int{5}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	LastBlock     uint64                 `protobuf:"varint,4,opt,name=last_block,json=lastBlock,proto3" json:"last_block,omitempty"`
	ActivePools   uint32                 `protobuf:"varint,5,opt,name=active_pools,json=activePools,proto3" json:"active_pools,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_aether_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_aether_proto_rawDescGZIP(), []int{6}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthCheckResponse) GetLastBlock() uint64 {
	if x != nil {
		return x.LastBlock
	}
	return 0
}

func (x *HealthCheckResponse) GetActivePools() uint32 {
	if x != nil {
		return x.ActivePools
	}
	return 0
}

type SetStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         SystemState            `protobuf:"varint,1,opt,name=state,proto3,enum=aether.SystemState" json:"state,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStateRequest) Reset() {
	*x = SetStateRequest{}
	mi := &file_proto_aether_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStateRequest) ProtoMessage() {}

func (x *SetStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStateRequest.ProtoReflect.Descriptor instead.
func (*SetStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_aether_proto_rawDescGZIP(), []int{7}
}

func (x *SetStateRequest) GetState() SystemState {
	if x != nil {
		return x.State
	}
	return SystemState_STATE_UNKNOWN
}

func (x *SetStateRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type SetStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PreviousState SystemState            `protobuf:"varint,2,opt,name=previous_state,json=previousState,proto3,enum=aether.SystemState" json:"previous_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetStateResponse) Reset() {
	*x = SetStateResponse{}
	mi := &file_proto_aether_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetStateResponse) ProtoMessage() {}

func (x *SetStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetStateResponse.ProtoReflect.Descriptor instead.
func (*SetStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_aether_proto_rawDescGZIP(), []int{8}
}

func (x *SetStateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetStateResponse) GetPreviousState() SystemState {
	if x != nil {
		return x.PreviousState
	}
	return SystemState_STATE_UNKNOWN
}

type ReloadConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigPath    string                 `protobuf:"bytes,1,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadConfigRequest) Reset() {
	*x = ReloadConfigRequest{}
	mi := &file_proto_aether_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadConfigRequest) ProtoMessage() {}

func (x *ReloadConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadConfigRequest.ProtoReflect.Descriptor instead.
func (*ReloadConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_aether_proto_rawDescGZIP(), []int{9}
}

func (x *ReloadConfigRequest) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

type ReloadConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PoolsLoaded   uint32                 `protobuf:"varint,2,opt,name=pools_loaded,json=poolsLoaded,proto3" json:"pools_loaded,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadConfigResponse) Reset() {
	*x = ReloadConfigResponse{}
	mi := &file_proto_aether_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadConfigResponse) ProtoMessage() {}

func (x *ReloadConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_aether_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadConfigResponse.ProtoReflect.Descriptor instead.
func (*ReloadConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_aether_proto_rawDescGZIP(), []int{10}
}

func (x *ReloadConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReloadConfigResponse) GetPoolsLoaded() uint32 {
	if x != nil {
		return x.PoolsLoaded
	}
	return 0
}

func (x *ReloadConfigResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_aether_proto protoreflect.FileDescriptor

const file_proto_aether_proto_rawDesc = "" +
	"\n" +
	"\x12proto/aether.proto\x12\x06aether\"\xf6\x01\n" +
	"\bSwapStep\x120\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x14.aether.ProtocolTypeR\bprotocol\x12!\n" +
	"\fpool_address\x18\x02 \x01(\fR\vpoolAddress\x12\x19\n" +
	"\btoken_in\x18\x03 \x01(\fR\atokenIn\x12\x1b\n" +
	"\ttoken_out\x18\x04 \x01(\fR\btokenOut\x12\x1b\n" +
	"\tamount_in\x18\x05 \x01(\fR\bamountIn\x12$\n" +
	"\x0emin_amount_out\x18\x06 \x01(\fR\fminAmountOut\x12\x1a\n" +
	"\bcalldata\x18\a \x01(\fR\bcalldata\"\xfa\x01\n" +
	"\x06ArbHop\x120\n" +
	"\bprotocol\x18\x01 \x01(\x0e2\x14.aether.ProtocolTypeR\bprotocol\x12!\n" +
	"\fpool_address\x18\x02 \x01(\fR\vpoolAddress\x12\x19\n" +
	"\btoken_in\x18\x03 \x01(\fR\atokenIn\x12\x1b\n" +
	"\ttoken_out\x18\x04 \x01(\fR\btokenOut\x12\x1b\n" +
	"\tamount_in\x18\x05 \x01(\fR\bamountIn\x12!\n" +
	"\fexpected_out\x18\x06 \x01(\fR\vexpectedOut\x12#\n" +
	"\restimated_gas\x18\a \x01(\x04R\festimatedGas\"\xaf\x03\n" +
	"\fValidatedArb\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\x04hops\x18\x02 \x03(\v2\x0e.aether.ArbHopR\x04hops\x12(\n" +
	"\x10total_profit_wei\x18\x03 \x01(\fR\x0etotalProfitWei\x12\x1b\n" +
	"\ttotal_gas\x18\x04 \x01(\x04R\btotalGas\x12 \n" +
	"\fgas_cost_wei\x18\x05 \x01(\fR\n" +
	"gasCostWei\x12$\n" +
	"\x0enet_profit_wei\x18\x06 \x01(\fR\fnetProfitWei\x12!\n" +
	"\fblock_number\x18\a \x01(\x04R\vblockNumber\x12!\n" +
	"\ftimestamp_ns\x18\b \x01(\x03R\vtimestampNs\x12'\n" +
	"\x0fflashloan_token\x18\t \x01(\fR\x0eflashloanToken\x12)\n" +
	"\x10flashloan_amount\x18\n" +
	" \x01(\fR\x0fflashloanAmount\x12&\n" +
	"\x05steps\x18\v \x03(\v2\x10.aether.SwapStepR\x05steps\x12\x1a\n" +
	"\bcalldata\x18\f \x01(\fR\bcalldata\"f\n" +
	"\x11SubmitArbResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12\x1f\n" +
	"\vbundle_hash\x18\x02 \x01(\tR\n" +
	"bundleHash\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"9\n" +
	"\x11StreamArbsRequest\x12$\n" +
	"\x0emin_profit_eth\x18\x01 \x01(\x01R\fminProfitEth\"\x14\n" +
	"\x12HealthCheckRequest\"\xb0\x01\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\x12\x1d\n" +
	"\n" +
	"last_block\x18\x04 \x01(\x04R\tlastBlock\x12!\n" +
	"\factive_pools\x18\x05 \x01(\rR\vactivePools\"T\n" +
	"\x0fSetStateRequest\x12)\n" +
	"\x05state\x18\x01 \x01(\x0e2\x13.aether.SystemStateR\x05state\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"h\n" +
	"\x10SetStateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12:\n" +
	"\x0eprevious_state\x18\x02 \x01(\x0e2\x13.aether.SystemStateR\rpreviousState\"6\n" +
	"\x13ReloadConfigRequest\x12\x1f\n" +
	"\vconfig_path\x18\x01 \x01(\tR\n" +
	"configPath\"i\n" +
	"\x14ReloadConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fpools_loaded\x18\x02 \x01(\rR\vpoolsLoaded\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error*~\n" +
	"\fProtocolType\x12\x14\n" +
	"\x10PROTOCOL_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"UNISWAP_V2\x10\x01\x12\x0e\n" +
	"\n" +
	"UNISWAP_V3\x10\x02\x12\r\n" +
	"\tSUSHISWAP\x10\x03\x12\t\n" +
	"\x05CURVE\x10\x04\x12\x0f\n" +
	"\vBALANCER_V2\x10\x05\x12\r\n" +
	"\tBANCOR_V3\x10\x06*S\n" +
	"\vSystemState\x12\x11\n" +
	"\rSTATE_UNKNOWN\x10\x00\x12\v\n" +
	"\aRUNNING\x10\x01\x12\f\n" +
	"\bDEGRADED\x10\x02\x12\n" +
	"\n" +
	"\x06PAUSED\x10\x03\x12\n" +
	"\n" +
	"\x06HALTED\x10\x042\x8b\x01\n" +
	"\n" +
	"ArbService\x12<\n" +
	"\tSubmitArb\x12\x14.aether.ValidatedArb\x1a\x19.aether.SubmitArbResponse\x12?\n" +
	"\n" +
	"StreamArbs\x12\x19.aether.StreamArbsRequest\x1a\x14.aether.ValidatedArb0\x012Q\n" +
	"\rHealthService\x12@\n" +
	"\x05Check\x12\x1a.aether.HealthCheckRequest\x1a\x1b.aether.HealthCheckResponse2\x9a\x01\n" +
	"\x0eControlService\x12=\n" +
	"\bSetState\x12\x17.aether.SetStateRequest\x1a\x18.aether.SetStateResponse\x12I\n" +
	"\fReloadConfig\x12\x1b.aether.ReloadConfigRequest\x1a\x1c.aether.ReloadConfigResponseB*Z(github.com/aether-arb/aether/internal/pbb\x06proto3"

var (
	file_proto_aether_proto_rawDescOnce sync.Once
	file_proto_aether_proto_rawDescData []byte
)

func file_proto_aether_proto_rawDescGZIP() []byte {
	file_proto_aether_proto_rawDescOnce.Do(func() {
		file_proto_aether_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_aether_proto_rawDesc), len(file_proto_aether_proto_rawDesc)))
	})
	return file_proto_aether_proto_rawDescData
}

var file_proto_aether_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_aether_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_aether_proto_goTypes = []any{
	(ProtocolType)(0),            // 0: aether.ProtocolType
	(SystemState)(0),             // 1: aether.SystemState
	(*SwapStep)(nil),             // 2: aether.SwapStep
	(*ArbHop)(nil),               // 3: aether.ArbHop
	(*ValidatedArb)(nil),         // 4: aether.ValidatedArb
	(*SubmitArbResponse)(nil),    // 5: aether.SubmitArbResponse
	(*StreamArbsRequest)(nil),    // 6: aether.StreamArbsRequest
	(*HealthCheckRequest)(nil),   // 7: aether.HealthCheckRequest
	(*HealthCheckResponse)(nil),  // 8: aether.HealthCheckResponse
	(*SetStateRequest)(nil),      // 9: aether.SetStateRequest
	(*SetStateResponse)(nil),     // 10: aether.SetStateResponse
	(*ReloadConfigRequest)(nil),  // 11: aether.ReloadConfigRequest
	(*ReloadConfigResponse)(nil), // 12: aether.ReloadConfigResponse
}
var file_proto_aether_proto_depIdxs = []int32{
	0,  // 0: aether.SwapStep.protocol:type_name -> aether.ProtocolType
	0,  // 1: aether.ArbHop.protocol:type_name -> aether.ProtocolType
	3,  // 2: aether.ValidatedArb.hops:type_name -> aether.ArbHop
	2,  // 3: aether.ValidatedArb.steps:type_name -> aether.SwapStep
	1,  // 4: aether.SetStateRequest.state:type_name -> aether.SystemState
	1,  // 5: aether.SetStateResponse.previous_state:type_name -> aether.SystemState
	4,  // 6: aether.ArbService.SubmitArb:input_type -> aether.ValidatedArb
	6,  // 7: aether.ArbService.StreamArbs:input_type -> aether.StreamArbsRequest
	7,  // 8: aether.HealthService.Check:input_type -> aether.HealthCheckRequest
	9,  // 9: aether.ControlService.SetState:input_type -> aether.SetStateRequest
	11, // 10: aether.ControlService.ReloadConfig:input_type -> aether.ReloadConfigRequest
	5,  // 11: aether.ArbService.SubmitArb:output_type -> aether.SubmitArbResponse
	4,  // 12: aether.ArbService.StreamArbs:output_type -> aether.ValidatedArb
	8,  // 13: aether.HealthService.Check:output_type -> aether.HealthCheckResponse
	10, // 14: aether.ControlService.SetState:output_type -> aether.SetStateResponse
	12, // 15: aether.ControlService.ReloadConfig:output_type -> aether.ReloadConfigResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_aether_proto_init() }
func file_proto_aether_proto_init() {
	if File_proto_aether_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_aether_proto_rawDesc), len(file_proto_aether_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_aether_proto_goTypes,
		DependencyIndexes: file_proto_aether_proto_depIdxs,
		EnumInfos:         file_proto_aether_proto_enumTypes,
		MessageInfos:      file_proto_aether_proto_msgTypes,
	}.Build()
	File_proto_aether_proto = out.File
	file_proto_aether_proto_goTypes = nil
	file_proto_aether_proto_depIdxs = nil
}
